version: '3.1'

volumes:
  db:

services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: <pg-user>
      POSTGRES_PASSWORD: <pg-password>
    volumes:
          - /postgres-data:/var/lib/postgresql/data